const employees = [
  {
    id: 1,
    name: "Employee One",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Weekly Report",
        description: "Submit weekly report to the team lead",
        date: "2025-08-01",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskNumber: "active1",
      },
      {
        title: "Team Meeting",
        description: "Participate in the weekly team meeting",
        date: "2025-08-02",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskNumber: "completed2",
      },
      {
        title: "Documentation Update",
        description: "Update outdated sections of the user manual",
        date: "2025-07-31",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskNumber: "active3",
      },
    ],
  },
  {
    id: 2,
    name: "Employee Two",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Code Review",
        description: "Review merge requests in the backend repo",
        date: "2025-08-03",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskNumber: "active1",
      },
      {
        title: "Release Deployment",
        description: "Deploy the new feature release to production",
        date: "2025-07-30",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskNumber: "completed2",
      },
      {
        title: "Test Case Writing",
        description: "Write automated tests for new components",
        date: "2025-08-01",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskNumber: "failed3",
      },
    ],
  },
  {
    id: 3,
    name: "Employee Three",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Mockup Design",
        description: "Design new UI mockups for dashboard",
        date: "2025-08-02",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskNumber: "active1",
      },
      {
        title: "Feedback Review",
        description: "Analyze customer feedback for recent features",
        date: "2025-07-29",
        category: "Research",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskNumber: "completed2",
      },
      {
        title: "Feature Implementation",
        description: "Implement requested user feature",
        date: "2025-08-03",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskNumber: "active3",
      },
    ],
  },
  {
    id: 4,
    name: "Employee Four",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Presentation Prep",
        description: "Create slides for the Q3 roadmap meeting",
        date: "2025-08-04",
        category: "Planning",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskNumber: "active1",
      },
      {
        title: "File Organization",
        description: "Clean and organize project files on the drive",
        date: "2025-07-31",
        category: "Admin",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskNumber: "completed2",
      },
      {
        title: "Server Debug",
        description: "Fix the server crash bug affecting auth service",
        date: "2025-08-01",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskNumber: "active3",
      },
    ],
  },
  {
    id: 5,
    name: "Employee Five",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Log Audit",
        description: "Audit application logs for security issues",
        date: "2025-08-02",
        category: "Security",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskNumber: "active1",
      },
      {
        title: "Database Cleanup",
        description: "Remove redundant entries and optimize tables",
        date: "2025-07-30",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskNumber: "completed2",
      },
      {
        title: "Backup Check",
        description: "Verify daily database backups and restore logs",
        date: "2025-08-01",
        category: "IT Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskNumber: "active3",
      },
      {
        title: "Account Reset",
        description: "Reset credentials for 5 locked-out users",
        date: "2025-07-31",
        category: "Support",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskNumber: "failed4",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    name: "Admin One",
    email: "admin@example.com",
    password: "123",
  },
];


export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  
 return{employees,admin}
  
};
